[package]
name = "bms_lv_rust"
version = "0.1.0"
edition = "2021"

[features]
default = []
ltc-hardware = []

[dependencies]
embassy-stm32 = { git = "https://github.com/embassy-rs/embassy.git", rev = "a2b2a3e190a244df16a9a8ec03d7fb9d91d8297c", features = [
    "stm32h563vi",
    "unstable-pac",
    "time-driver-any",
] }

embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "a2b2a3e190a244df16a9a8ec03d7fb9d91d8297c", features = [
    "platform-cortex-m",
    "executor-thread",
] }

embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "a2b2a3e190a244df16a9a8ec03d7fb9d91d8297c" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "a2b2a3e190a244df16a9a8ec03d7fb9d91d8297c" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy.git", rev = "a2b2a3e190a244df16a9a8ec03d7fb9d91d8297c" }
panic-probe = "0.3.1"
static_cell = "2.1.0"
cortex-m = { version = "0.7.9", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.6"
embedded-can = "0.4"
heapless = { version = "0.8", default-features = false }
libm = "0.2.15"

[profile.release]
debug = 2
opt-level = "s"
lto = true

[profile.dev]
opt-level = 1
