[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "sh post_build.sh"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
EMBASSY_USB_MAX_INTERFACE_COUNT        = "16"
EMBASSY_USB_MAX_HANDLER_COUNT          = "16"
EMBASSY_EXECUTOR_TASK_ARENA_SIZE       = "30000"
