name: Docs

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Speeds up rebuilds (optional ma consigliato)
      - uses: Swatinem/rust-cache@v2

      - name: Build documentation
        run: cargo doc --no-deps --document-private-items

      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: target/doc
